# Generated by Django 4.0.3 on 2022-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_added',
            field=models.DateTimeField(null=True),
        ),
    ]
